Add missing icon_app.png
To fix:
```
Error: Asset not found: /assets/icon_app.png for platform: null
    at /node_modules/metro/src/Assets.js:188:13
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/node_modules/metro/src/Assets.js:52:24)
    at _next (/node_modules/metro/src/Assets.js:72:9)
```